services:
  postgres:
    container_name: postgres_container
    image: postgres:13
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${PG_USER}" ]
      interval: 30s
      timeout: 10s
      retries: 5

  pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin_container
      environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
        PGADMIN_CONFIG_SERVER_MODE: 'False'
      ports:
        - "5050:80"
      volumes:
        - ./pgadmin:/var/lib/pgadmin
      depends_on:
        - postgres
      healthcheck:
        test: [ "CMD-SHELL", "curl -f http://localhost:80/ || exit 1" ]
        interval: 30s
        timeout: 10s
        retries: 5

volumes:
    pgdata:
      driver: local
    pgadmin-data:
      driver: local